### ISSUE TITLE
Cannot find module '@pawjs/srcset/webpack'

### ISSUE THREAD

**Issue by sultanaslam** [Atyantik/react-pwa#116]
After Installing npm packages when run the command **npm start** getting this error

  module.js:557
    throw err;
    ^

Error: Cannot find module '@pawjs/srcset/webpack'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/Users/Sultan/Projects/new/react-pwa/src/webpack.js:2:1)
    at Module._compile (module.js:660:30)
    at Module._compile (/mnt/c/Users/Sultan/Projects/new/react-pwa/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:671:10)
    at Object.newLoader [as .js] (/mnt/c/Users/Sultan/Projects/new/react-pwa/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:573:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-pwa@2.2.0 start: `pawjs --env=development start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-pwa@2.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/linuxsultan/.npm/_logs/2018-11-08T09_30_20_455Z-debug.log`

**Comment by tirthbodawala** [comment]
@sultanaslam this has been solved. Sorry was solved all along the same day but missed to update it.
