### ISSUE TITLE
Cannot find module React

### ISSUE THREAD

**Issue by ldevalbray** [Atyantik/react-pwa#120]
Hello, I have got this issue when starting my app with react-pwa :

```
Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/louis/example-pawjs-redux/node_modules/react-hot-loader/dist/react-hot-loader.production.min.js:1:179)
    at Module._compile (module.js:652:30)
    at Module._compile (/home/louis/example-pawjs-redux/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/home/louis/example-pawjs-redux/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)

```

When I try to install react, an error is thrown saying there are multiple copies of React (I imagine, one from react-pwa). How comes it does not find it the first time ?

Here is my package.json for now (did not edit the infos linking to your website for now) : 

```
{
  "name": "example-pawjs-redux",
  "version": "1.0.0",
  "description": "Example on using Redux with PawJS",
  "scripts": {
    "start": "pawjs --env=development start",
    "build": "pawjs --env=production --config=prod.pawconfig.json build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Atyantik/example-pawjs-redux.git"
  },
  "author": {
    "name": "Atyantik Technologies",
    "email": "admin@atyantik.com",
    "url": "https://www.atyantik.com/"
  },
  "engines": {
    "node": ">=10.11.0"
  },
  "contributors": [
    {
      "name": "Tirth Bodawala",
      "email": "tirthbodawala@atyantik.com",
      "url": "https://www.atyantik.com/"
    },
    {
      "name": "Yash Thakur",
      "email": "thakur.yash514@gmail.com",
      "url": "http://yashthakur.in/"
    }
  ],
  "devDependencies": {
    "@pawjs/pawjs": "^2.2.6",
    "@pawjs/redux": "^2.1.6",
    "@pawjs/sass": "^2.1.7",
    "axios": "^0.18.0",
    "pdfmake": "^0.1.40",
    "quill-image-resize-module-react": "^3.0.0",
    "raf": "^3.4.1",
    "react": "^16.7.0",
    "react-animate-on-scroll": "^2.1.5",
    "react-autobind": "^1.0.6",
    "react-circular-progressbar": "^1.0.0",
    "react-credit-cards": "^0.7.0",
    "react-document-meta": "^3.0.0-beta.2",
    "react-facebook-login-component": "^0.9.2",
    "react-geocode": "^0.1.2",
    "react-geosuggest": "^2.9.0",
    "react-quill": "^1.3.3",
    "react-redux": "^5.0.7",
    "react-scroll-to-component": "^1.0.2",
    "react-slick": "^0.23.2",
    "react-stars": "^2.2.5",
    "redux": "^4.0.1",
    "redux-form": "^8.1.0",
    "socket.io-client": "^2.2.0",
    "sweetalert2": "^7.33.1",
    "tween": "^0.9.0",
    "webpack": "^4.28.3"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/Atyantik/example-pawjs-redux/issues"
  },
  "homepage": "https://github.com/Atyantik/example-pawjs-redux#readme",
  "dependencies": {
    "connect-mongo": "^2.0.3",
    "express-session": "^1.15.6",
    "mongoose": "^5.4.1"
  }
}

```

Thank you very much !

**Comment by tirthbodawala** [comment]
I shall check that. Thanks for reporting it.

**Comment by ldevalbray** [comment]
Thank you for your time and reactivity ! Do you think you would be able to recreate the issue ? 
If it could help, I could give you access to my actual code. I am quite stuck ^^

**Comment by tirthbodawala** [comment]
@ldevalbray I was able to recreate this issue and this is caused as PawJS already has its own React version installed.

Once can get it solved by the following steps:
1) remove react from package.json
```
npm r react react-dom --save
```
2) Remove `package-lock.json` and `node_modules`
```
rm -rf package-lock.json && rm -rf node_modules
```

3) Re-Install all packages
```
npm i 
```

Upgrading to latest pawjs version is also a good idea so
```
npm i @pawjs/pawjs@latest --save
```

Hope the above helps
