### ISSUE TITLE
FATAL ERROR: JavaScript heap out of memory, allocation failure

### ISSUE THREAD

**Issue by tongrow** [Atyantik/react-pwa#128]
Hello, I have got this issue when build my app:

```
> react-pwa@2.2.3 build C:\JavaCodes\MyProject\react-pwa
> pawjs --no-cache --config=./prod-pawconfig.json --env=production build

[BABEL] Note: The code generator has deoptimised the styling of C:\JavaCodes\MyProject\react-pwa\node_modules\lodash\lodash.js as it exceeds the max of 500KB.

===================================================
  Building application...
  This may take time depending on the application size.
  Thank you for your patience.
===================================================

clean-webpack-plugin: C:\JavaCodes\MyProject\react-pwa\dist has been removed.

<--- Last few GCs --->

[4712:000001B6F7C26430]    92305 ms: Scavenge 1373.7 (1423.7) -> 1373.0 (1424.7) MB, 4.8 / 0.0 ms  (average mu = 0.261, current mu = 0.237) allocation failure
[4712:000001B6F7C26430]    92339 ms: Scavenge 1374.1 (1424.7) -> 1373.5 (1425.2) MB, 33.1 / 0.0 ms  (average mu = 0.261, current mu = 0.237) allocation failure
[4712:000001B6F7C26430]    92347 ms: Scavenge 1374.2 (1425.2) -> 1373.6 (1425.7) MB, 6.8 / 0.0 ms  (average mu = 0.261, current mu = 0.237) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000003B94785C5C1]
    1: StubFrame [pc: 000003B94781757A]
Security context: 0x00b6b541e6e1 <JSObject>
    2: SourceMapConsumer_allGeneratedPositionsFor [0000031EE07FB791] [C:\JavaCodes\MyProject\react-pwa\node_modules\source-map\lib\source-map-consumer.js:~178] [pc=000003B9483DBF10](this=0x0012f076ac21 <BasicSourceMapConsumer map = 000001AF2E289319>,aArgs=0x007a54982249 <Object map = 000001CA8B215971>)
    ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6D4E60EFA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 00007FF6D4E3A296 node::MakeCallback+4518
 3: 00007FF6D4E3AC80 node_module_register+2160
 4: 00007FF6D50D09BE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF6D50D08EF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF6D560E954 v8::internal::Heap::MaxHeapGrowingFactor+11476
 7: 00007FF6D56050B7 v8::internal::ScavengeJob::operator=+25543
 8: 00007FF6D560362C v8::internal::ScavengeJob::operator=+18748
 9: 00007FF6D560C5A7 v8::internal::Heap::MaxHeapGrowingFactor+2343
10: 00007FF6D560C626 v8::internal::Heap::MaxHeapGrowingFactor+2470
11: 00007FF6D51AF447 v8::internal::Factory::NewFillerObject+55
12: 00007FF6D524712A v8::internal::WasmJs::Install+29530
13: 000003B94785C5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! react-pwa@2.2.3 build: `pawjs --no-cache --config=./prod-pawconfig.json --env=production build`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the react-pwa@2.2.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2019-02-21T18_05_13_819Z-debug.log
```

**It can be reproduced from scratch**, just use react-pwa@2.2.3 or 2.2.2, or 2.1.4 from master branch.

This error appears with:
npm 6.4.1
node 10.15.1

With node 8.11.2 you can't see the error, but script starts using 1GB of RAM and stay at line:
`clean-webpack-plugin: C:\JavaCodes\MyProject\react-pwa\dist has been removed.`
Also I catched `Assertion failed: handle->pending_signum == 0, file src\win\signal.c, line 272` once, with node 8.11.2, after the script terminating with `Ctrl + C`.

System:
Windows 10 x64

Log 

> 2019-02-21T18_05_13_819Z-debug.log

 reffered from above:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle react-pwa@2.2.3~prebuild: react-pwa@2.2.3
6 info lifecycle react-pwa@2.2.3~build: react-pwa@2.2.3
7 verbose lifecycle react-pwa@2.2.3~build: unsafe-perm in lifecycle true
8 verbose lifecycle react-pwa@2.2.3~build: PATH: *PATH here*
9 verbose lifecycle react-pwa@2.2.3~build: CWD: C:\JavaCodes\MyProject\react-pwa
10 silly lifecycle react-pwa@2.2.3~build: Args: [ '/d /s /c',
10 silly lifecycle   'pawjs --no-cache --config=./prod-pawconfig.json --env=production build' ]
11 silly lifecycle react-pwa@2.2.3~build: Returned: code: 134  signal: null
12 info lifecycle react-pwa@2.2.3~build: Failed to exec build script
13 verbose stack Error: react-pwa@2.2.3 build: `pawjs --no-cache --config=./prod-pawconfig.json --env=production build`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid react-pwa@2.2.3
15 verbose cwd C:\JavaCodes\MyProject\react-pwa
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 134
22 error react-pwa@2.2.3 build: `pawjs --no-cache --config=./prod-pawconfig.json --env=production build`
22 error Exit status 134
23 error Failed at the react-pwa@2.2.3 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
```

Similar errors found at:
https://github.com/netlify/netlify-cms-widget-starter/issues/3
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/118 (include memory usage screens)

_Hope for the earliest possible solution. Thanks._

**Comment by tongrow** [comment]
From `report.20190222.232148.9428.001.json`

```
  "javascriptStack": {
    "message": "No stack.",
    "stack": [
      "Unavailable."
    ]
  },
  "nativeStack": [
    {
      "pc": "0x00007ff7bd2bdd6e",
      "symbol": "std::basic_ostream<char,std::char_traits<char> >::operator<<+9902"
    },
    {
      "pc": "0x00007ff7bd2bcc36",
      "symbol": "std::basic_ostream<char,std::char_traits<char> >::operator<<+5494"
    },
    {
      "pc": "0x00007ff7bd2bc4a2",
      "symbol": "std::basic_ostream<char,std::char_traits<char> >::operator<<+3554"
    },
    {
      "pc": "0x00007ff7bd3ba3ed",
      "symbol": "uv_loop_fork+83805"
    },
    {
      "pc": "0x00007ff7bd7b0f1e",
      "symbol": "v8::internal::FatalProcessOutOfMemory+798"
    },
    {
      "pc": "0x00007ff7bd7b0e57",
      "symbol": "v8::internal::FatalProcessOutOfMemory+599"
    },
    {
      "pc": "0x00007ff7bd860e74",
      "symbol": "v8::internal::Heap::RootIsImmortalImmovable+14900"
    },
    {
      "pc": "0x00007ff7bd856994",
      "symbol": "v8::internal::Heap::CollectGarbage+7556"
    },
    {
      "pc": "0x00007ff7bd855068",
      "symbol": "v8::internal::Heap::CollectGarbage+1112"
    },
    {
      "pc": "0x00007ff7bd85eab7",
      "symbol": "v8::internal::Heap::RootIsImmortalImmovable+5751"
    },
    {
      "pc": "0x00007ff7bd85eb36",
      "symbol": "v8::internal::Heap::RootIsImmortalImmovable+5878"
    },
    {
      "pc": "0x00007ff7bd9e78e1",
      "symbol": "v8::internal::Factory::NewFillerObject+49"
    },
    {
      "pc": "0x00007ff7bdaa0cea",
      "symbol": "v8::internal::StoreBuffer::StoreBufferOverflow+27082"
    },
    {
      "pc": "0x000001a55ba50461",
      "symbol": ""
    }
  ],
  "javascriptHeap": {
    "totalMemory": 1489092608,
    "totalCommittedMemory": 1489092608,
    "usedMemory": 1452755464,
    "availableMemory": 38720432,
    "memoryLimit": 1526909922,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 524288,
        "committedMemory": 524288,
        "capacity": 515584,
        "used": 33520,
        "available": 482064
      },
      "new_space": {
        "memorySize": 2097152,
        "committedMemory": 2097152,
        "capacity": 1031168,
        "used": 167888,
        "available": 863280
      },
      "old_space": {
        "memorySize": 1456672768,
        "committedMemory": 1456672768,
        "capacity": 1426870288,
        "used": 1426485664,
        "available": 384624
      },
      "code_space": {
        "memorySize": 3670016,
        "committedMemory": 3670016,
        "capacity": 3426176,
        "used": 3426176,
        "available": 0
      },
      "map_space": {
        "memorySize": 3682304,
        "committedMemory": 3682304,
        "capacity": 1735520,
        "used": 1735520,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 22446080,
        "committedMemory": 22446080,
        "capacity": 57897160,
        "used": 20906696,
        "available": 36990464
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 0,
        "used": 0,
        "available": 0
      }
    }
  },
```

**Comment by tongrow** [comment]
@yash-thakur @ldevalbray

**Comment by fsiatama** [comment]
in package.json

replace 


```
"scripts": {
    "start": "pawjs --no-cache --env=development start",
    "build": "node --max_old_space_size=4096  ./node_modules/.bin//../@pawjs/pawjs/paw.js --no-cache --config=./prod-pawconfig.json --env=production build",
    "build:demo": "node --max_old_space_size=4096  ./node_modules/.bin//../@pawjs/pawjs/paw.js --no-cache --config=./demo-pawconfig.json --env=production build",
    "lint": "pawjs lint",
    "test": "pawjs --no-cache test",
    "snyk-protect": "snyk protect",
    "prepare": "npm run snyk-protect"
  },
```

**Comment by x5engine** [comment]
for people using react-scripts

`    "build": "react-scripts --max_old_space_size=4096 build",
`
https://github.com/facebook/create-react-app/issues/4536
