### ISSUE TITLE
pngquant can't be build and libpng-dev is not existed in npm.

### ISSUE THREAD

**Issue by boas19910115** [Atyantik/react-pwa#133]
```
C:\fabryque\react-pwa>npm i

> pngquant-bin@5.0.1 postinstall C:\fabryque\react-pwa\node_modules\pngquant-bin
> node lib/install.js

  ‼ Command failed: C:\fabryque\react-pwa\node_modules\pngquant-bin\vendor\pngquant.exe --version


  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (C:\fabryque\react-pwa\node_modules\execa\index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN @pawjs/srcset@2.1.0-beta.0 requires a peer of file-loader@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-router-config@4.4.0-beta.6 requires a peer of react-router@4.4.0-beta.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-pwa@2.2.3 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

**Comment by tirthbodawala** [comment]
@boas19910115 Can you please mention details about your operating system and working environment along with node version?
