### ISSUE TITLE
throwing Unhandled promise rejection error

### ISSUE THREAD

**Issue by priyanshujain** [Atyantik/react-pwa#166]
Please find the logs

```

> react-pwa@2.2.8 start /Users/PJ/Documents/Workspace/oss/doctricFE
> pawjs --no-cache --env=development start



=========================================================
  Compiling files.
  This may take time depending on the application size.
  Thank you for your patience.
=========================================================

⬢ pawjs: Hash: d0ec3c741f2491d2b2ab
Child server:
    Hash: d0ec3c741f2491d2b2ab
    Time: 7073ms
    Built at: 2019-12-25 21:38:34
                                                                   Asset      Size  Chunks             Chunk Names
               build/images/0a3a3ee486af139328225006d2194c64-dog-cat.jpg  72.4 KiB          [emitted]  
               build/images/18087f0d9a458518dd35888b87310507-dog-cat.jpg   217 KiB          [emitted]  
              build/images/32ed777ab1fe34b666e3b9a86a70c214-dog-cat.webp    21 KiB          [emitted]  
      build/images/3a8136a792cfe525ff82f7488883fa1d-pwa-icon-512x512.png  11.6 KiB          [emitted]  
             build/images/3a8136a792cfe525ff82f7488883fa1d-react-pwa.png  11.6 KiB          [emitted]  
              build/images/3d58a9745f4c4290ea6284f965b3b201-dog-cat.webp  30.3 KiB          [emitted]  
               build/images/3f15a79a47affa012bb66ce7358529d4-dog-cat.jpg  47.6 KiB          [emitted]  
               build/images/4838751591a8e8d02e87157402b7503f-dog-cat.jpg  14.8 KiB          [emitted]  
    build/images/61e7625c4871f9c2aa98767f2a5f3e7c-home-splash-screen.png  23.4 KiB          [emitted]  
      build/images/715d8373bad8c370c2922f09e90f4224-pwa-icon-192x192.png  4.78 KiB          [emitted]  
               build/images/960ebbbaddc3a142543ed3704f3217f9-dog-cat.jpg   100 KiB          [emitted]  
               build/images/a519802052fcefe5a8e691fc32b79f68-dog-cat.jpg  29.6 KiB          [emitted]  
    build/images/a77c503c0d57c75a90a475bc8f6cba0e-image-optimization.png  2.39 MiB          [emitted]  
              build/images/c83a2ab832abf5c7760ac8645928d721-dog-cat.webp  39.8 KiB          [emitted]  
              build/images/cc07d3f84ad49fe415a00316b68304b6-features.png   114 KiB          [emitted]  
              build/images/d4b91a04e44298f5f6dfec040fe790b3-dog-cat.webp  7.62 KiB          [emitted]  
              build/images/decbc7080f5db3f5c0fd548a629f9c10-dog-cat.webp    14 KiB          [emitted]  
      build/images/e2bad7093258bf1417e588a7b73dbb61-skeleton-loading.png  13.2 KiB          [emitted]  
      build/images/f9cc46ed43970e8d720342d08b3b88b2-css-global-local.png  62.2 KiB          [emitted]  
                 build/images/faebe23649d4785d13fc9449766d6367-login.png  22.1 KiB          [emitted]  
                                                              server.css  80 bytes    main  [emitted]  main
                                                               server.js  4.42 MiB    main  [emitted]  main
⬡ pawjs: Compiled with warnings.
⬡ pawjs: Hash: cfccac4951f96f2bced9
Child web:
    Hash: cfccac4951f96f2bced9
    Time: 11005ms
    Built at: 2019-12-25 21:38:38
                                                             Asset      Size          Chunks                         Chunk Names
               images/0a3a3ee486af139328225006d2194c64-dog-cat.jpg  72.4 KiB                  [emitted]              
               images/18087f0d9a458518dd35888b87310507-dog-cat.jpg   217 KiB                  [emitted]              
              images/32ed777ab1fe34b666e3b9a86a70c214-dog-cat.webp    21 KiB                  [emitted]              
      images/3a8136a792cfe525ff82f7488883fa1d-pwa-icon-512x512.png  11.6 KiB                  [emitted]              
              images/3d58a9745f4c4290ea6284f965b3b201-dog-cat.webp  30.3 KiB                  [emitted]              
               images/3f15a79a47affa012bb66ce7358529d4-dog-cat.jpg  47.6 KiB                  [emitted]              
               images/4838751591a8e8d02e87157402b7503f-dog-cat.jpg  14.8 KiB                  [emitted]              
    images/61e7625c4871f9c2aa98767f2a5f3e7c-home-splash-screen.png  23.4 KiB                  [emitted]              
      images/715d8373bad8c370c2922f09e90f4224-pwa-icon-192x192.png  4.78 KiB                  [emitted]              
               images/960ebbbaddc3a142543ed3704f3217f9-dog-cat.jpg   100 KiB                  [emitted]              
               images/a519802052fcefe5a8e691fc32b79f68-dog-cat.jpg  29.6 KiB                  [emitted]              
    images/a77c503c0d57c75a90a475bc8f6cba0e-image-optimization.png  2.39 MiB                  [emitted]              
              images/c83a2ab832abf5c7760ac8645928d721-dog-cat.webp  39.8 KiB                  [emitted]              
              images/cc07d3f84ad49fe415a00316b68304b6-features.png   114 KiB                  [emitted]              
              images/d4b91a04e44298f5f6dfec040fe790b3-dog-cat.webp  7.62 KiB                  [emitted]              
              images/decbc7080f5db3f5c0fd548a629f9c10-dog-cat.webp    14 KiB                  [emitted]              
      images/e2bad7093258bf1417e588a7b73dbb61-skeleton-loading.png  13.2 KiB                  [emitted]              
      images/f9cc46ed43970e8d720342d08b3b88b2-css-global-local.png  62.2 KiB                  [emitted]              
                 images/faebe23649d4785d13fc9449766d6367-login.png  22.1 KiB                  [emitted]              
                                        js/2fb72b5c4d2f761849d0.js  4.16 KiB              10  [emitted] [immutable]  
                                        js/33d6162302305cbb1308.js  41.3 KiB               5  [emitted] [immutable]  
                                        js/76481b612bc9e43e963d.js  37.9 KiB               2  [emitted] [immutable]  
                                        js/801f975ffe7719f16b65.js  31.2 KiB               7  [emitted] [immutable]  
                                        js/910f794a1c50d86c965a.js   814 KiB               9  [emitted] [immutable]  
                                        js/949a22ba1e91e03f1476.js  59.3 KiB               1  [emitted] [immutable]  
                                        js/b5428efb228c24409c20.js  9.36 MiB  vendors~client  [emitted] [immutable]  vendors~client
                                        js/cfccac4951f96f2bced9.js   140 KiB          client  [emitted] [immutable]  client
                                        js/d48c618cd39eabd422b5.js  69.8 KiB               0  [emitted] [immutable]  
                                        js/d5a2e5a15aceb9fd0785.js    52 KiB               4  [emitted] [immutable]  
                                        js/dd5b3fab60ea94b9ac04.js    24 KiB               8  [emitted] [immutable]  
                                        js/ded9f403d4a3811d5307.js  34.2 KiB               3  [emitted] [immutable]  
                                        js/e51484b344a149ef6776.js  38.3 KiB               6  [emitted] [immutable]  
             precache-manifest.74f2e0ace61dbe614ccfa1e0035da974.js  2.15 KiB                  [emitted]              
                                                             sw.js   3.1 KiB                  [emitted]              
⬡ pawjs: Compiled successfully.


===================================================
  Listening to http://0.0.0.0:9090
  Open the above url in your browser.
===================================================
(node:47283) UnhandledPromiseRejectionWarning: TypeError: Promise.all(...).then(...).catch(...).finally is not a function
    at __webpack_exports__.default (webpack-internal:///./node_modules/@pawjs/pawjs/src/utils/loadable.ts:82:13)
    at Function.init [as preload] (webpack-internal:///./node_modules/@pawjs/pawjs/src/components/Loadable.tsx:46:13)
    at currentPageRoutes.forEach (webpack-internal:///./node_modules/@pawjs/pawjs/src/server/handler.tsx:178:39)
    at Array.forEach (<anonymous>)
    at ServerHandler.run (webpack-internal:///./node_modules/@pawjs/pawjs/src/server/handler.tsx:173:23)
    at <anonymous>
(node:47283) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:47283) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by priyanshujain** [comment]
It was due to old version of node. I mistakenly moved to 8.12.
