### ISSUE TITLE
Unable to `npm start` at all

### ISSUE THREAD

**Issue by 14rego** [Atyantik/react-pwa#168]
node 10.5
npm 6.1.0
Same errors on two different machines:
```
me$ npm install
 ...
me$ npm start

> react-pwa@2.2.8 start /Users/me/react-pwa
> pawjs --no-cache --env=development start


=========================================================
  Compiling files.
  This may take time depending on the application size.
  Thank you for your patience.
=========================================================

(node:84449) UnhandledPromiseRejectionWarning: ModuleBuildError: Module build failed (from ./node_modules/webp-loader/index.js):
Error: spawn /Users/me/app/node_modules/cwebp-bin/vendor/cwebp EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    at /Users/me/app/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/me/app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/me/app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/me/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/me/app/node_modules/webp-loader/index.js:32:9
(node:84449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:84449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:84449) UnhandledPromiseRejectionWarning: ModuleBuildError: Module build failed (from ./node_modules/webp-loader/index.js):
Error: spawn /Users/me/app/node_modules/cwebp-bin/vendor/cwebp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    at /Users/me/app/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/me/app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/me/app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/me/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/me/app/node_modules/webp-loader/index.js:32:9
(node:84449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by tirthbodawala** [comment]
@14rego which OS are you using?

**Comment by 14rego** [comment]
@tirthbodawala OSX 10.15.2 on my laptop. Not exactly sure the build on the other, but similar or the same. I had the same trouble with newer versions of Node (13), so I backed down a few to be sure the problem wasn't that my Node was too new.

**Comment by 14rego** [comment]
I didn't fix it, I just don't care enough to troubleshoot if I'm the only person with this problem. I'll use something else. Thanks anyway.

**Comment by 14rego** [comment]
This was my issue, in case it's helpful to anyone else. But it's not actually fixed, only closed. Their solution is to change versions.
https://github.com/fsevents/fsevents/issues/181

**Comment by 14rego** [comment]
This was my issue, FWIW. The issue is closed, but not fixed. It's suggested you update versions.
https://github.com/fsevents/fsevents/issues/181
