### ISSUE TITLE
Can't npm start

### ISSUE THREAD

**Issue by kien-pham** [Atyantik/react-pwa#181]
Hello,

I got this issue when npm start

```
pawjs --no-cache --env=development start

sh: pawjs: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! react-pwa@2.2.9 start: `pawjs --no-cache --env=development start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-pwa@2.2.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2020-04-07T13_56_46_527Z-debug.log
```

on the log file

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-pwa@2.2.9~prestart: react-pwa@2.2.9
6 info lifecycle react-pwa@2.2.9~start: react-pwa@2.2.9
7 verbose lifecycle react-pwa@2.2.9~start: unsafe-perm in lifecycle true
8 verbose lifecycle react-pwa@2.2.9~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Volumes/Data/Coding/react-redux-universal-hot-example/react-pwa/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle react-pwa@2.2.9~start: CWD: /Volumes/Data/Coding/react-redux-universal-hot-example/react-pwa
10 silly lifecycle react-pwa@2.2.9~start: Args: [ '-c', 'pawjs --no-cache --env=development start' ]
11 info lifecycle react-pwa@2.2.9~start: Failed to exec start script
12 verbose stack Error: react-pwa@2.2.9 start: `pawjs --no-cache --env=development start`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid react-pwa@2.2.9
14 verbose cwd /Volumes/Data/Coding/react-redux-universal-hot-example/react-pwa
15 verbose Darwin 19.3.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v10.16.0
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error react-pwa@2.2.9 start: `pawjs --no-cache --env=development start`
23 error spawn ENOENT
24 error Failed at the react-pwa@2.2.9 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by adamcanray** [comment]
same issue.

**Comment by tirthbodawala** [comment]
@adamcanray @kien-pham Can you please share the node version you are using?

**Comment by tirthbodawala** [comment]
Please use NodeJS > 12.x to solve the above issue.

**Comment by salescnet** [comment]
Still facing the same issue..

**Comment by tirthbodawala** [comment]
Please share the node version

**Comment by salescnet** [comment]
problem resolved.

**Comment by salescnet** [comment]
problem resolved on linux.

**Comment by salescnet** [comment]
problem resolved on linux.

**Comment by salescnet** [comment]
problem resolved.

**Comment by salescnet** [comment]
Jus install npm i @pawjs/pawjs
