### ISSUE TITLE
not able to start server, installation was successfull

### ISSUE THREAD

**Issue by kalandher** [Atyantik/react-pwa#186]
getting below error when i do npm start

(node:2361) UnhandledPromiseRejectionWarning: TypeError: Promise.all(...).then(...).catch(...).finally is not a function
    at __webpack_exports__.default (webpack-internal:///./node_modules/@pawjs/pawjs/src/utils/loadable.ts:82:13)
    at Function.init [as preload] (webpack-internal:///./node_modules/@pawjs/pawjs/src/components/Loadable.tsx:46:13)
    at currentPageRoutes.forEach (webpack-internal:///./node_modules/@pawjs/pawjs/src/server/handler.tsx:177:39)
    at Array.forEach (<anonymous>)
    at ServerHandler.run (webpack-internal:///./node_modules/@pawjs/pawjs/src/server/handler.tsx:172:23)
    at <anonymous>
(node:2361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tirthbodawala** [comment]
@kalandher please let me know your node and npm version

**Comment by tirthbodawala** [comment]
Closing due to inactivity
