### ISSUE TITLE
npm run dev failed to start - Could not find a declaration file for module '@reactpwa/core/start

### ISSUE THREAD

**Issue by leostereo** [Atyantik/react-pwa#226]
Hello , guys  after clone and install dependencies im getting following msg after doing "npm run dev"
`[cli] src/index.ts(24,39): error TS7016: Could not find a declaration file for module '@reactpwa/core/start'. '/home/leostereo/projects/react-pwa/packages/core/lib/node/start.js' implicitly has an 'any' type.
[cli]   Try `npm i --save-dev @types/reactpwa__core` if it exists or add a new declaration (.d.ts) file containing `declare module '@reactpwa/core/start';`
[cli] src/index.ts(77,39): error TS7016: Could not find a declaration file for module '@reactpwa/core/build'. '/home/leostereo/projects/react-pwa/packages/core/lib/node/build.js' implicitly has an 'any' type.
[cli]   Try `npm i --save-dev @types/reactpwa__core` if it exists or add a new declaration (.d.ts) file containing `declare module '@reactpwa/core/build';`
[cli]
[cli] DTS Build failed
[cli] Error: error occured in dts build
[cli]     at Worker.<anonymous> (/home/leostereo/projects/react-pwa/node_modules/tsup/dist/index.js:2281:26)
[cli]     at Worker.emit (node:events:513:28)
[cli]     at MessagePort.<anonymous> (node:internal/worker:238:53)
[cli]     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:738:20)
[cli]     at exports.emitMessage (node:internal/per_context/messageport:23:28)
[cli] RollupError: Failed to compile. Check the logs above.
[cli]     at error (/home/leostereo/projects/react-pwa/node_modules/rollup/dist/shared/rollup.js:210:30)
[cli]     at Object.error (/home/leostereo/projects/react-pwa/node_modules/rollup/dist/shared/rollup.js:23975:20)
[cli]     at Object.error (/home/leostereo/projects/react-pwa/node_modules/rollup/dist/shared/rollup.js:23220:42)
[cli]     at generateDtsFromTs (/home/leostereo/projects/react-pwa/node_modules/tsup/dist/rollup.js:7484:22)
[cli]     at /home/leostereo/projects/react-pwa/node_modules/tsup/dist/rollup.js:7491:59
[cli]     at _nullishCoalesce (/home/leostereo/projects/react-pwa/node_modules/tsup/dist/rollup.js:1:198)
[cli]     at Object.transform (/home/leostereo/projects/react-pwa/node_modules/tsup/dist/rollup.js:7491:18)
[cli]     at /home/leostereo/projects/react-pwa/node_modules/rollup/dist/shared/rollup.js:24176:40`

Any ideas  ?

**Comment by tirthbodawala** [comment]
Hey, are you trying to enhance the core packages? If not, and just trying to utilise reactpwa to create a project, then please follow the README.md

```

git clone https://github.com/Atyantik/react-pwa-boilerplate.git my-pwa && cd my-pwa
```
