### ISSUE TITLE
building app the app is not working out of the box

### ISSUE THREAD

**Issue by samueljim** [Atyantik/react-pwa#48]
I am running into issues where building the app with yarn build returns errors like this

ERROR in ../core/node_modules/css-loader?{"modules":true,"localIdentName":"[name]_[local]_[hash:base64:5]","sourceMap":false,"minimize":true,"importLoaders":2}!../core/node_modules/postcss-loader/lib?{"sourceMap":false,"path":"C://Users//thesa//Documents//react-pwa//core//node_modules"}!../core/node_modules/sass-loader/lib/loader.js?{"outputStyle":"compressed","sourceMap":false,"sourceMapContents":false}!./app/components/about/about.scss
Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`
    at error (C:\Users\thesa\Documents\react-pwa\core\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:37:11)
    at C:\Users\thesa\Documents\react-pwa\core\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:222:9
    at Array.forEach (<anonymous>)
    at browserslist (C:\Users\thesa\Documents\react-pwa\core\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:196:13)
    at cleanBrowsersList (C:\Users\thesa\Documents\react-pwa\core\node_modules\postcss-merge-rules\node_modules\caniuse-api\dist\utils.js:56:59)
    at setBrowserScope (C:\Users\thesa\Documents\react-pwa\core\node_modules\postcss-merge-rules\node_modules\caniuse-api\dist\index.js:29:43)
    at Object.<anonymous> (C:\Users\thesa\Documents\react-pwa\core\node_modules\postcss-merge-rules\node_modules\caniuse-api\dist\index.js:91:1)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\thesa\Documents\react-pwa\core\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\thesa\Documents\react-pwa\core\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:7:19)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\thesa\Documents\react-pwa\core\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\thesa\Documents\react-pwa\core\node_modules\postcss-merge-rules\dist\index.js:21:28)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\thesa\Documents\react-pwa\core\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
 @ ./app/components/about/about.scss 4:14-233
 @ ./app/components/about/about.js
 @ ./pages/about.js

**Comment by dav-is** [comment]
Appears to be an issue with yarn on windows. Using npm should allow it to work (if this is the same issue I’ve seen), but this is obviously an issue.

**Comment by samueljim** [comment]
Using npm changes nothing to do with the build sadly. When i use npm install fails when it gets to webpack

C:\Users\thesa\Documents\react-pwa\core\uglifyjs -> C:\Users\thesa\Documents\react-pwa\core\node_modules\uglify-js\bin\uglifyjs
npm ERR! path C:\Users\thesa\Documents\react-pwa\core\webpack
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall open
npm ERR! EISDIR: illegal operation on a directory, open 'C:\Users\thesa\Documents\react-pwa\core\webpack'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thesa\AppData\Roaming\npm-cache\_logs\2017-11-19T23_03_46_161Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963228
npm ERR! ReactPWA@0.2.2 postinstall: `npm install --prefix ./core`
npm ERR! Exit status 4294963228
npm ERR!
npm ERR! Failed at the ReactPWA@0.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thesa\AppData\Roaming\npm-cache\_logs\2017-11-19T23_03_46_330Z-debug.log

**Comment by dav-is** [comment]
I guess that means it’s a separate issue than https://github.com/Atyantik/react-pwa/issues/43

**Comment by samueljim** [comment]
Something web-pack related. in the last version i was getting an issue with uglifyjs also

**Comment by tirthbodawala** [comment]
@samueljim Can you please mention nodejs and yarn version you are using? and this is only during build right? or happens during development as well?

**Comment by tirthbodawala** [comment]
I have corrected the npm command for windows as npm --prefix is not working as expected in windows! we would rather cd the directory and call the command.
