### ISSUE TITLE
since core update i can't add new packages or npm start

### ISSUE THREAD

**Issue by samueljim** [Atyantik/react-pwa#54]
the code will run up untill i add a new node package
module.js:538
    throw err;
    ^

Error: Cannot find module '../../directories'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Users/thesa/Documents/ia-jn/core/webpack/dev.babel.js:26:1)
    at Module._compile (module.js:635:30)
    at loader (C:\Users\thesa\Documents\ia-jn\core\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\thesa\Documents\ia-jn\core\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)

OR

module.js:538
    throw err;
    ^

Error: Cannot find module '../../directories'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Users/thesa/Documents/ia-jn/core/webpack/dev.babel.js:26:1)
    at Module._compile (module.js:635:30)
    at loader (C:\Users\thesa\Documents\ia-jn\core\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\thesa\Documents\ia-jn\core\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)

Either way there's an issue

**Comment by tirthbodawala** [comment]
Hey @samueljim can you please share the solution as well?

**Comment by samueljim** [comment]
Just don't delete the directories file like i did 🤒 
I can't run built code now  

C:\Users\thesa\Documents\ia-jn\dist\server.js:1
(function (exports, require, module, __filename, __dirname) { !function(e){function t(n){if(r[n])return r[n].exports;var o=r[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,t),o.l=!0,o.exports}var r={};t.m=e,t.c=r,t.d=function(e,r,n){t.o(e,r)||Object.defineProperty(e,r,{configurable:!1,enumerable:!0,get:n})},t.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(r,"a",r),r},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="/",t(t.s=722)}([function(e,t,r){e.exports=r(1402)()},function(e,t,r){"use strict";e.exports=r(1383)},function(e,t,r){"use strict";function n(e){return Object.getPrototypeOf(e)===Buffer.prototype?e:e instanceof ArrayBuffer?Buffer.from(e):Buffer.from(e.buffer,e.byteOffset,e.byteLength)}function o(e){return e?e[a]:null}function i(e){return e?e[s]:null}const a=Symbol("wrapper"),s=Symbol("impl"),u=Symbol("SameObject caches"),l=Symbol("internal"),p=Object.getPrototy

ReferenceError: navigator is not defined
    at Object.defineProperty.value (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:3574777)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
    at Object.defineProperty.value (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:3561874)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
    at Object.defineProperty.value (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:3557999)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
    at Object.defineProperty.value (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:3550789)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
    at Object.defineProperty.value (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:3550343)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
