### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by samueljim** [Atyantik/react-pwa#55]
(function (exports, require, module, __filename, __dirname) { !function(e){function t(n){if(r[n])return r[n].exports;var o=r[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,t),o.l=!0,o.exports}var r={};t.m=e,t.c=r,t.d=function(e,r,n){t.o(e,r)||Object.defineProperty(e,r,{configurable:!1,enumerable:!0,get:n})},t.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(r,"a",r),r},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="/",t(t.s=904)}([function(e,t,r){e.exports=r(1577)()},function(e,t,r){"use strict";e.exports=r(1559)},function(e,t,r){"use strict";function n(e){return Object.getPrototypeOf(e)===Buffer.prototype?e:e instanceof ArrayBuffer?Buffer.from(e):Buffer.from(e.buffer,e.byteOffset,e.byteLength)}function o(e){return e?e[a]:null}function i(e){return e?e[s]:null}const a=Symbol("wrapper"),s=Symbol("impl"),u=Symbol("SameObject caches"),l=Symbol("internal"),p=Object.getPrototy

ReferenceError: navigator is not defined
    at Object.defineProperty.value (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:4132995)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
    at Object.defineProperty.value (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:4120092)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
    at Object.defineProperty.value (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:4116217)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
    at Object.defineProperty.value (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:4109007)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
    at Object.defineProperty.value (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:4108559)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)

**Comment by tirthbodawala** [comment]
Hi @samueljim, Well you are using some plugin that is utilizing window. window.navigator during SSR, well it is not a good practice to use any plugins/libraries. If it is unavoidable, you can create a PR for adding polyfill for window.navigator in /core/src/server/dom-polyfill.js something like:
```
//.... previous code
if (typeof window === "undefined") {
  const window = (new JSDOM("", { runScripts: "outside-only" })).window;
  
  // Adding custom event
  if ( typeof window.CustomEvent !== "function" ) {
    const CustomEvent = function ( event, params ) {
      params = params || { bubbles: false, cancelable: false, detail: undefined };
      let evt = document.createEvent( "CustomEvent" );
      evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
      return evt;
    };
    CustomEvent.prototype = window.Event.prototype;
    window.CustomEvent = CustomEvent;
  }
  
  // Add fetch to window
  window.fetch = fetch;
  
  const { document } = window;
  if (window.navigator) {
    global.navigator = window.navigator;
  } else {
    // ... some polyfill we need for server! 
    global.navgator = {};
  }
  
  global.window = window;
  global.document = document;
  global.CustomEvent = window.CustomEvent;
}
```

**Comment by dav-is** [comment]
This question need to be put into some sort of FAQ.

**Comment by samueljim** [comment]
the same result happens when code is unchanged from a direct pull

**Comment by tirthbodawala** [comment]
@samueljim Sorry didn't understand the direct pull query. What happens with direct pull?

**Comment by samueljim** [comment]
when i pull the project and install and build it it gives this output 
i have not added any library's

**Comment by samueljim** [comment]
@tirthbodawala after i make your changes i get this
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\thesa\Documents\ia-jn\dist\public\index.html'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at e.exports.e (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:4547742)
    at Object.<anonymous> (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:3535675)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
    at Object.<anonymous> (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:2006816)
    at t (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:163)
    at C:\Users\thesa\Documents\ia-jn\dist\server.js:1:514
    at Object.<anonymous> (C:\Users\thesa\Documents\ia-jn\dist\server.js:1:525)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)

**Comment by samueljim** [comment]
i have worked out the issue was my computer
Now i don't know why the built version looks different from the original
